version: "3.9"
services:
  web:
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./dist:/var/www/html
    ports:
      - 80:80
    env_file:
      - .env
networks:
  default:
    name: net-webservices
